---
- name: Add or update user password
  hosts: AnsibleTestAzure
  become: true
  tasks:
    - name: Change "george" password
      user:
        name: george
        update_password: always
        password: "{{ newpassword | password_hash('sha512') }}"

# ansible-playbook changepass.yml --extra-vars newpassword=1
