apiVersion: v1
kind: Pod
metadata:
  name: prometheus
spec:
  containers:
    - name: prometheus-main
      image: docker.io/prom/prometheus:latest
      args:
        - "--config.file=/etc/prometheus/prometheus.yaml"
      ports:
        - containerPort: 9090
        - hostPort: 9090
      volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-config
      restartPolicy: Always

    - name: node-exporter
      image: quay.io/prometheus/node-exporter:latest
      args:
        - "--path.rootfs=/host"
      ports:
        - containerPort: 9100
        - hostPort: 9100
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /host
          name: host-root
          readOnly: true

  volumes:
    - name: prometheus-config
      hostPath:
        path: /home/dj/git/devops/prometheus
        type: Directory
    - name: host-root
      hostPath:
        path: /
        type: Directory
