---
- name: Create and mount storage
  hosts: AnsibleTestAzure

  tasks:
    - name: Create new partition
      parted:
        name: Files
        label: gpt
        device: /dev/sdb
        number: 1
        state: preasent
        part_start: 1MiB
        part_end: 1GiB

    - name: Create xfs filesystem
      filesystem:
        dev: /dev/sdb1
        fstype: xfs

    - name: Create mount directory
      file:
        path: /data
        state: directory

    - name: mount the filesystem
      mount:
        src: /dev/sdb1
        fstype: xfs
        state: mounted
        path: /data