---
- name: Installing and Running Apache
  hosts: AnsibleTestAzure
  become: true

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      notify:
        - restart apache

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted