---
- hosts: control
  become: true
  tasks:
    - name: install tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - curl

    - name: ensure nginx started
      service: name=nginx state=started enabled=yes
  